=== Felipe-ies/Cheatsheets/Marcas/XSD_del_XML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"></xs:element>
                            <xs:element name="autor" type="xs:string"></xs:element>
                            <xs:element name="fecha_pub" type="xs:gYear"></xs:element>
                            <xs:choice>
                                <xs:element name="precio_dolares" type="xs:decimal"></xs:element>
                                <xs:element name="precio_euros" type="xs:decimal"></xs:element>
                            </xs:choice>
                        </xs:sequence>
                        <xs:attribute name="id">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:pattern value="[0-9]+"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Felipe-ies/Cheatsheets/Marcas/XML_con_XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="XSD_del_XML.xsd">
    <libro id="1"> 
        <titulo>1984</titulo> 
        <autor>George Orwell</autor>
        <fecha_pub>1949</fecha_pub>
        <precio_dolares>25</precio_dolares>
    </libro>
    <libro id="2">
        <titulo>El Principito</titulo>
        <autor>Saint Exuperi</autor>
        <fecha_pub>1975</fecha_pub>
        <precio_euros>20</precio_euros>
    </libro>
</biblioteca>
